In [49]:
import numpy as numpy
import pandas as pandas 
import matplotlib.pyplot as plt 
import seaborn as sns 
sns.set()

In [50]:
data_preprsd = pandas.read_csv('Modified_csv.csv')


In [51]:
data_preprsd

reason_1  reason_2  reason_3  reason_4  Month  Day of week  \
0           0         0         0         1      7            1   
1           0         0         0         0      7            1   
2           0         0         0         0      7            2   
3           1         0         0         0      7            3   
4           0         0         0         0      7            3   
..        ...       ...       ...       ...    ...          ...   
695         1         0         0         0      5            2   
696         1         0         0         0      5            2   
697         1         0         0         0      5            3   
698         0         0         0         0      5            3   
699         0         0         0         1      5            3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                 30          0         2     1                          4  
1                 31          0         1     0                          0  
2                 31          0         0     0                          2  
3                 24          0         2     0                          4  
4                 30          0         2     1                          2  
..               ...        ...       ...   ...                        ...  
695               22          1         2     0                          8  
696               24          0         1     2                          3  
697               25          1         0     0                          8  
698               25          1         0     0                          2  
699               25          0         1     1                          2  

[700 rows x 15 columns]

In [52]:
# making copy
data_c = data_preprsd.copy()


In [53]:
data_preprsd['Absenteeism Time in Hours'].median()

3.0

In [54]:
# generating targets
targets = numpy.where(data_preprsd['Absenteeism Time in Hours']>data_preprsd['Absenteeism Time in Hours'].median(),1,0)

In [55]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [56]:
data_preprsd['Excessive Absenteeism'] = targets
data_preprsd.head()

reason_1  reason_2  reason_3  reason_4  Month  Day of week  \
0         0         0         0         1      7            1   
1         0         0         0         0      7            1   
2         0         0         0         0      7            2   
3         1         0         0         0      7            3   
4         0         0         0         0      7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [57]:
targets.sum()/targets.shape[0]


0.45571428571428574

In [58]:
data_with_targets =  data_preprsd.drop(['Absenteeism Time in Hours','Day of week','Daily Work Load Average','Distance to Work'], axis = 1)

In [59]:
data_with_targets.head()

reason_1  reason_2  reason_3  reason_4  Month  Transportation Expense  Age  \
0         0         0         0         1      7                     289   33   
1         0         0         0         0      7                     118   50   
2         0         0         0         0      7                     179   38   
3         1         0         0         0      7                     279   39   
4         0         0         0         0      7                     289   33   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [60]:
## select the inputs for the regressio
unscaled_input = data_with_targets.iloc[:,:-1]
unscaled_input.head()

reason_1  reason_2  reason_3  reason_4  Month  Transportation Expense  Age  \
0         0         0         0         1      7                     289   33   
1         0         0         0         0      7                     118   50   
2         0         0         0         0      7                     179   38   
3         1         0         0         0      7                     279   39   
4         0         0         0         0      7                     289   33   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1

## satandardizing the data

In [61]:
# from sklearn.preprocessing import StandardScaler
# scaler_object = StandardScaler()



In [62]:
'''

we are defining our own standard scaler as custom scaler to improve the explaining power of model so that we 
the dummy variables wont get scaled on our output (interpretsbility)



'''



'\n\nwe are defining our own standard scaler as custom scaler to improve the explaining power of model so that we \nthe dummy variables wont get scaled on our output (interpretsbility)\n\n\n\n'

In [63]:
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler
class CustomScaler(BaseEstimator,TransformerMixin):
     def __init__(self,columns,copy=True,with_mean = True, with_std = True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns  = columns
        self.mean_ = None
        self.var_ = None


     def fit(self,X,y = None):
            self.scaler.fit(X[self.columns],y)
            self.mean_ = numpy.mean(X[self.columns])
            self.var_ = numpy.var(X[self.columns])
            return self 

     def  transform(self,X,y=None,copy =  None):
            init_col_order = X.columns
            X_scaled = pandas.DataFrame(self.scaler.transform(X[self.columns]),columns = self.columns)
            X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
            return pandas.concat([X_not_scaled,X_scaled],axis = 1)[init_col_order]

In [64]:
unscaled_input.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [65]:
# columns_to_scaled = ['Month','Day of week', 'Transportation Expense', 'Distance to Work', 'Age',
#        'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pets']

In [66]:
columns_to_omit = ['reason_1', 'reason_2', 'reason_3', 'reason_4','Education']

In [67]:
columns_to_scaled = [x for x in unscaled_input.columns.values if x not in columns_to_omit ]

In [68]:
absenteeism_scaler = CustomScaler(columns_to_scaled)

In [69]:
absenteeism_scaler.fit(unscaled_input)

CustomScaler(columns=['Month', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [70]:
# scaler_object.fit(unscaled_input)


In [71]:
scaled_input = absenteeism_scaler.transform(unscaled_input)

In [72]:
scaled_input

reason_1  reason_2  reason_3  reason_4     Month  Transportation Expense  \
0           0         0         0         1  0.182726                1.005844   
1           0         0         0         0  0.182726               -1.574681   
2           0         0         0         0  0.182726               -0.654143   
3           1         0         0         0  0.182726                0.854936   
4           0         0         0         0  0.182726                1.005844   
..        ...       ...       ...       ...       ...                     ...   
695         1         0         0         0 -0.388293               -0.654143   
696         1         0         0         0 -0.388293                0.040034   
697         1         0         0         0 -0.388293                1.624567   
698         0         0         0         0 -0.388293                0.190942   
699         0         0         0         1 -0.388293                1.036026   

          Age  Body Mass Index  Education  Children      Pets  
0   -0.536062         0.767431          0  0.880469  0.268487  
1    2.130803         1.002633          0 -0.019280 -0.589690  
2    0.248310         1.002633          0 -0.919030 -0.589690  
3    0.405184        -0.643782          0  0.880469 -0.589690  
4   -0.536062         0.767431          0  0.880469  0.268487  
..        ...              ...        ...       ...       ...  
695  0.562059        -1.114186          1  0.880469 -0.589690  
696 -1.320435        -0.643782          0 -0.019280  1.126663  
697 -1.320435        -0.408580          1 -0.919030 -0.589690  
698 -0.692937        -0.408580          1 -0.919030 -0.589690  
699  0.562059        -0.408580          0 -0.019280  0.268487  

[700 rows x 11 columns]

## splitting the data into test and train

In [73]:
from sklearn.model_selection import train_test_split


In [74]:
#train_test_split(scaled_input,targets)

In [75]:
x_train,x_test,y_train,y_test = train_test_split(scaled_input,targets,train_size = 0.8,random_state = 20)
print(x_train.shape,x_test.shape)

(560, 11) (140, 11)


In [76]:
print(y_train.shape,y_test.shape)

(560,) (140,)


In [77]:
## logistic regression using sklearn
from sklearn.linear_model import  LogisticRegression
reg = LogisticRegression()

In [78]:
reg.fit(x_train,y_train)


LogisticRegression()

In [79]:
## checking the accuracy
reg.score(x_train,y_train)

0.7464285714285714

In [80]:
## checking accuracy

predicted_output = reg.predict(x_train)


In [81]:
predicted_output == y_train

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True, False,  True, False,  True,  True,  True,
        True,  True,

In [82]:
acc  = numpy.sum(predicted_output == y_train)/predicted_output.shape[0]
acc

0.7464285714285714

## coff and intercept

In [83]:
reg.intercept_

array([-0.81258831])

In [84]:
reg.coef_

array([[ 1.75317707, -0.02276885,  2.51573816, -0.03021215,  0.19268815,
         0.51251671, -0.07460196,  0.18151168, -0.01484993,  0.28750931,
        -0.3433442 ]])

In [85]:
arr =unscaled_input.columns.values

In [86]:
summary_table = pandas.DataFrame(columns=['Features'],data= arr)
summary_table

Features
0                 reason_1
1                 reason_2
2                 reason_3
3                 reason_4
4                    Month
5   Transportation Expense
6                      Age
7          Body Mass Index
8                Education
9                 Children
10                    Pets

In [87]:
summary_table['coefficients'] = numpy.transpose(reg.coef_)

In [88]:
summary_table

Features  coefficients
0                 reason_1      1.753177
1                 reason_2     -0.022769
2                 reason_3      2.515738
3                 reason_4     -0.030212
4                    Month      0.192688
5   Transportation Expense      0.512517
6                      Age     -0.074602
7          Body Mass Index      0.181512
8                Education     -0.014850
9                 Children      0.287509
10                    Pets     -0.343344

In [89]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Features  coefficients
0                Intercept     -0.812588
1                 reason_1      1.753177
2                 reason_2     -0.022769
3                 reason_3      2.515738
4                 reason_4     -0.030212
5                    Month      0.192688
6   Transportation Expense      0.512517
7                      Age     -0.074602
8          Body Mass Index      0.181512
9                Education     -0.014850
10                Children      0.287509
11                    Pets     -0.343344

In [90]:
summary_table = summary_table.drop([0],axis = 0)
summary_table

Features  coefficients
1                 reason_1      1.753177
2                 reason_2     -0.022769
3                 reason_3      2.515738
4                 reason_4     -0.030212
5                    Month      0.192688
6   Transportation Expense      0.512517
7                      Age     -0.074602
8          Body Mass Index      0.181512
9                Education     -0.014850
10                Children      0.287509
11                    Pets     -0.343344

In [91]:
summary_table.index = summary_table.index - 1


In [92]:
summary_table

Features  coefficients
0                 reason_1      1.753177
1                 reason_2     -0.022769
2                 reason_3      2.515738
3                 reason_4     -0.030212
4                    Month      0.192688
5   Transportation Expense      0.512517
6                      Age     -0.074602
7          Body Mass Index      0.181512
8                Education     -0.014850
9                 Children      0.287509
10                    Pets     -0.343344

In [93]:
summary_table.to_csv('data.csv',index = False)

In [94]:
summary_table['odds_ratio']  = numpy.exp(summary_table.coefficients)

In [95]:
summary_table

Features  coefficients  odds_ratio
0                 reason_1      1.753177    5.772915
1                 reason_2     -0.022769    0.977488
2                 reason_3      2.515738   12.375741
3                 reason_4     -0.030212    0.970240
4                    Month      0.192688    1.212505
5   Transportation Expense      0.512517    1.669488
6                      Age     -0.074602    0.928113
7          Body Mass Index      0.181512    1.199029
8                Education     -0.014850    0.985260
9                 Children      0.287509    1.333103
10                    Pets     -0.343344    0.709394

In [96]:
summary_table.sort_values('odds_ratio',ascending=False)

Features  coefficients  odds_ratio
2                 reason_3      2.515738   12.375741
0                 reason_1      1.753177    5.772915
5   Transportation Expense      0.512517    1.669488
9                 Children      0.287509    1.333103
4                    Month      0.192688    1.212505
7          Body Mass Index      0.181512    1.199029
8                Education     -0.014850    0.985260
1                 reason_2     -0.022769    0.977488
3                 reason_4     -0.030212    0.970240
6                      Age     -0.074602    0.928113
10                    Pets     -0.343344    0.709394

In [97]:
scaled_input

reason_1  reason_2  reason_3  reason_4     Month  Transportation Expense  \
0           0         0         0         1  0.182726                1.005844   
1           0         0         0         0  0.182726               -1.574681   
2           0         0         0         0  0.182726               -0.654143   
3           1         0         0         0  0.182726                0.854936   
4           0         0         0         0  0.182726                1.005844   
..        ...       ...       ...       ...       ...                     ...   
695         1         0         0         0 -0.388293               -0.654143   
696         1         0         0         0 -0.388293                0.040034   
697         1         0         0         0 -0.388293                1.624567   
698         0         0         0         0 -0.388293                0.190942   
699         0         0         0         1 -0.388293                1.036026   

          Age  Body Mass Index  Education  Children      Pets  
0   -0.536062         0.767431          0  0.880469  0.268487  
1    2.130803         1.002633          0 -0.019280 -0.589690  
2    0.248310         1.002633          0 -0.919030 -0.589690  
3    0.405184        -0.643782          0  0.880469 -0.589690  
4   -0.536062         0.767431          0  0.880469  0.268487  
..        ...              ...        ...       ...       ...  
695  0.562059        -1.114186          1  0.880469 -0.589690  
696 -1.320435        -0.643782          0 -0.019280  1.126663  
697 -1.320435        -0.408580          1 -0.919030 -0.589690  
698 -0.692937        -0.408580          1 -0.919030 -0.589690  
699  0.562059        -0.408580          0 -0.019280  0.268487  

[700 rows x 11 columns]

In [98]:
# from sklearn.base import BaseEstimator,TransformerMixin
# from sklearn.preprocessing import StandardScaler
# class CustomScaler(BaseEstimator,TransformerMixin):
#     def __init__(self,columns,copy=True,with_mean = True, with_std = True):
#         self.scaler = StandardScaler(copy,with_mean,with_std)
#         self.columns  = columns
#         self.mean_ = None
#         self.var_ = None


#         def fit(self,X,y = None):
#             self.scaler.fit(X[self.columns],y)
#             self.mean_ = np.mean(x[self.columns])
#             self.var_ = np.var(X[self.columns])
#             return self 

#         def  transform(self,X,y=None,copy =  None):
#             init_col_order = X.columns
#             X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]),columns = self.columns)
#             X_not_scaled = X.loc[:,-columns.isin(self.columns)]
#             return pd.concat([X_not_scaled,X_scaled],axis = 1)[init_col_order]

## testing the model

In [99]:
reg.score(x_test,y_test)

0.7214285714285714

In [102]:
predict_proba = reg.predict_proba(x_test)

In [103]:
predict_proba

array([[0.6944678 , 0.3055322 ],
       [0.59396986, 0.40603014],
       [0.47226761, 0.52773239],
       [0.77923359, 0.22076641],
       [0.41771584, 0.58228416],
       [0.37234179, 0.62765821],
       [0.36585955, 0.63414045],
       [0.11572913, 0.88427087],
       [0.82169636, 0.17830364],
       [0.73320329, 0.26679671],
       [0.11417158, 0.88582842],
       [0.03195029, 0.96804971],
       [0.06399282, 0.93600718],
       [0.16891025, 0.83108975],
       [0.75722997, 0.24277003],
       [0.54792363, 0.45207637],
       [0.67743068, 0.32256932],
       [0.13838566, 0.86161434],
       [0.37622651, 0.62377349],
       [0.0536977 , 0.9463023 ],
       [0.72061758, 0.27938242],
       [0.77923359, 0.22076641],
       [0.40754233, 0.59245767],
       [0.40754233, 0.59245767],
       [0.23449339, 0.76550661],
       [0.7777861 , 0.2222139 ],
       [0.50766983, 0.49233017],
       [0.79157336, 0.20842664],
       [0.15124627, 0.84875373],
       [0.77923359, 0.22076641],
       [0.

In [104]:
predict_proba[:,1]

array([0.3055322 , 0.40603014, 0.52773239, 0.22076641, 0.58228416,
       0.62765821, 0.63414045, 0.88427087, 0.17830364, 0.26679671,
       0.88582842, 0.96804971, 0.93600718, 0.83108975, 0.24277003,
       0.45207637, 0.32256932, 0.86161434, 0.62377349, 0.9463023 ,
       0.27938242, 0.22076641, 0.59245767, 0.59245767, 0.76550661,
       0.2222139 , 0.49233017, 0.20842664, 0.84875373, 0.22076641,
       0.87495421, 0.59037963, 0.65299093, 0.89649285, 0.22076641,
       0.91044235, 0.18650699, 0.22818091, 0.37462189, 0.58228416,
       0.21144787, 0.49465686, 0.20377914, 0.58228416, 0.77790181,
       0.139535  , 0.6557913 , 0.31198007, 0.24607552, 0.20242048,
       0.64193782, 0.55552703, 0.62765821, 0.31226155, 0.80265762,
       0.44024685, 0.84796577, 0.23257836, 0.50780609, 0.52154697,
       0.70361027, 0.61471352, 0.31464404, 0.25777682, 0.18569521,
       0.28886409, 0.21501677, 0.19113431, 0.80632362, 0.85977565,
       0.18650699, 0.51405105, 0.87538634, 0.44839562, 0.52577

## pickling or saving reg variable

In [106]:
import pickle

In [107]:
with open('model','wb') as file:
    pickle.dump(reg,file)


In [109]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)